
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgrliliqewdqblbbswsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZncmxpbGlxZXdkcWJsYmJzd3NuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NjE5MzUsImV4cCI6MjA1ODIzNzkzNX0.oFwMZT4UX1zMlAibGvNQIuzWkRjpb0lKtU8FHwq_qKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
